import moment from 'moment';

export const mockUser = {
  id: 'user_001',
  name: 'Rizki Budiman',
  email: 'rizki@mobilejaga.id',
  phone: '+62 812-3456-7890',
  avatar: null,
  plan: 'Premium',
  planExpiry: '2026-12-31',
  joinDate: '2023-01-15',
  twoFactorEnabled: true,
  biometricEnabled: true,
  storageUsed: 68,
  storageTotal: 100,
};

export const mockCameras = [
  {
    id: 'cam_001',
    name: 'Depan Rumah',
    location: 'Pintu Depan',
    status: 'online',
    isRecording: true,
    hasMotion: false,
    isLive: true,
    batteryLevel: null,
    resolution: '4K (3840x2160)',
    fps: 30,
    nightVision: true,
    audioEnabled: true,
    motionDetection: true,
    autoRecord: true,
    ip: '192.168.1.101',
    mac: 'AA:BB:CC:DD:EE:01',
    firmware: 'v2.4.1',
    model: 'SecureCam Pro 4K',
    brand: 'MobileJaga',
    installDate: '2023-06-15',
    lastSeen: moment().subtract(2, 'minutes').toISOString(),
    thumbnail: null,
    streamUrl: null,
    angle: 120,
    zoom: 1,
    pan: 0,
    tilt: 0,
  },
  {
    id: 'cam_002',
    name: 'Garasi',
    location: 'Samping Kiri',
    status: 'online',
    isRecording: false,
    hasMotion: true,
    isLive: true,
    batteryLevel: null,
    resolution: '1080p (1920x1080)',
    fps: 25,
    nightVision: true,
    audioEnabled: false,
    motionDetection: true,
    autoRecord: false,
    ip: '192.168.1.102',
    mac: 'AA:BB:CC:DD:EE:02',
    firmware: 'v2.3.0',
    model: 'SecureCam HD',
    brand: 'MobileJaga',
    installDate: '2023-06-15',
    lastSeen: moment().subtract(1, 'minutes').toISOString(),
    thumbnail: null,
    streamUrl: null,
    angle: 90,
    zoom: 1,
    pan: 0,
    tilt: 0,
  },
  {
    id: 'cam_003',
    name: 'Ruang Tamu',
    location: 'Interior Depan',
    status: 'online',
    isRecording: true,
    hasMotion: false,
    isLive: true,
    batteryLevel: null,
    resolution: '2K (2560x1440)',
    fps: 30,
    nightVision: false,
    audioEnabled: true,
    motionDetection: true,
    autoRecord: true,
    ip: '192.168.1.103',
    mac: 'AA:BB:CC:DD:EE:03',
    firmware: 'v2.4.1',
    model: 'SecureCam Indoor 2K',
    brand: 'MobileJaga',
    installDate: '2023-08-20',
    lastSeen: moment().subtract(30, 'seconds').toISOString(),
    thumbnail: null,
    streamUrl: null,
    angle: 130,
    zoom: 1,
    pan: 0,
    tilt: 0,
  },
  {
    id: 'cam_004',
    name: 'Taman Belakang',
    location: 'Eksterior Belakang',
    status: 'offline',
    isRecording: false,
    hasMotion: false,
    isLive: false,
    batteryLevel: 12,
    resolution: '1080p (1920x1080)',
    fps: 20,
    nightVision: true,
    audioEnabled: false,
    motionDetection: false,
    autoRecord: false,
    ip: '192.168.1.104',
    mac: 'AA:BB:CC:DD:EE:04',
    firmware: 'v2.2.5',
    model: 'SecureCam Outdoor',
    brand: 'MobileJaga',
    installDate: '2023-09-10',
    lastSeen: moment().subtract(3, 'hours').toISOString(),
    thumbnail: null,
    streamUrl: null,
    angle: 110,
    zoom: 1,
    pan: 0,
    tilt: 0,
  },
  {
    id: 'cam_005',
    name: 'Dapur',
    location: 'Interior Belakang',
    status: 'online',
    isRecording: false,
    hasMotion: false,
    isLive: true,
    batteryLevel: null,
    resolution: '1080p (1920x1080)',
    fps: 25,
    nightVision: false,
    audioEnabled: true,
    motionDetection: true,
    autoRecord: false,
    ip: '192.168.1.105',
    mac: 'AA:BB:CC:DD:EE:05',
    firmware: 'v2.4.0',
    model: 'SecureCam Indoor',
    brand: 'MobileJaga',
    installDate: '2024-01-05',
    lastSeen: moment().subtract(1, 'minutes').toISOString(),
    thumbnail: null,
    streamUrl: null,
    angle: 100,
    zoom: 1,
    pan: 0,
    tilt: 0,
  },
  {
    id: 'cam_006',
    name: 'Pintu Gerbang',
    location: 'Eksterior Depan',
    status: 'online',
    isRecording: true,
    hasMotion: true,
    isLive: true,
    batteryLevel: null,
    resolution: '4K (3840x2160)',
    fps: 30,
    nightVision: true,
    audioEnabled: true,
    motionDetection: true,
    autoRecord: true,
    ip: '192.168.1.106',
    mac: 'AA:BB:CC:DD:EE:06',
    firmware: 'v2.4.1',
    model: 'SecureCam Gate Pro',
    brand: 'MobileJaga',
    installDate: '2023-11-20',
    lastSeen: moment().subtract(10, 'seconds').toISOString(),
    thumbnail: null,
    streamUrl: null,
    angle: 160,
    zoom: 1,
    pan: 0,
    tilt: 0,
  },
];

export const mockAlerts = [
  {
    id: 'alert_001',
    cameraId: 'cam_006',
    cameraName: 'Pintu Gerbang',
    type: 'motion',
    title: 'Gerakan Terdeteksi',
    message: 'Ada gerakan mencurigakan di area pintu gerbang',
    severity: 'high',
    isRead: false,
    timestamp: moment().subtract(5, 'minutes').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_002',
    cameraId: 'cam_004',
    cameraName: 'Taman Belakang',
    type: 'battery',
    title: 'Baterai Kritis',
    message: 'Baterai kamera Taman Belakang tersisa 12%, segera isi ulang',
    severity: 'high',
    isRead: false,
    timestamp: moment().subtract(30, 'minutes').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_003',
    cameraId: 'cam_004',
    cameraName: 'Taman Belakang',
    type: 'offline',
    title: 'Kamera Offline',
    message: 'Kamera Taman Belakang tidak dapat terhubung',
    severity: 'high',
    isRead: false,
    timestamp: moment().subtract(3, 'hours').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_004',
    cameraId: 'cam_002',
    cameraName: 'Garasi',
    type: 'motion',
    title: 'Gerakan di Garasi',
    message: 'Gerakan terdeteksi di area garasi',
    severity: 'medium',
    isRead: true,
    timestamp: moment().subtract(4, 'hours').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_005',
    cameraId: 'cam_001',
    cameraName: 'Depan Rumah',
    type: 'recording',
    title: 'Rekaman Dimulai',
    message: 'Rekaman otomatis dimulai karena deteksi gerakan',
    severity: 'low',
    isRead: true,
    timestamp: moment().subtract(6, 'hours').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_006',
    cameraId: 'cam_003',
    cameraName: 'Ruang Tamu',
    type: 'system',
    title: 'Update Firmware',
    message: 'Firmware v2.5.0 tersedia untuk kamera Ruang Tamu',
    severity: 'low',
    isRead: true,
    timestamp: moment().subtract(1, 'days').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_007',
    cameraId: 'cam_006',
    cameraName: 'Pintu Gerbang',
    type: 'motion',
    title: 'Gerakan Malam Hari',
    message: 'Gerakan terdeteksi di pintu gerbang pukul 02:30',
    severity: 'high',
    isRead: true,
    timestamp: moment().subtract(1, 'days').subtract(2, 'hours').toISOString(),
    thumbnail: null,
  },
  {
    id: 'alert_008',
    cameraId: 'cam_001',
    cameraName: 'Depan Rumah',
    type: 'motion',
    title: 'Tamu Terdeteksi',
    message: 'Seseorang terdeteksi di depan rumah',
    severity: 'medium',
    isRead: true,
    timestamp: moment().subtract(2, 'days').toISOString(),
    thumbnail: null,
  },
];

export const mockRecordings = [
  {
    id: 'rec_001',
    cameraId: 'cam_001',
    date: moment().format('YYYY-MM-DD'),
    startTime: '07:30:00',
    endTime: '07:45:23',
    duration: '15:23',
    size: '245 MB',
    type: 'motion',
    thumbnail: null,
  },
  {
    id: 'rec_002',
    cameraId: 'cam_001',
    date: moment().format('YYYY-MM-DD'),
    startTime: '12:15:00',
    endTime: '12:22:10',
    duration: '7:10',
    size: '112 MB',
    type: 'manual',
    thumbnail: null,
  },
  {
    id: 'rec_003',
    cameraId: 'cam_001',
    date: moment().subtract(1, 'days').format('YYYY-MM-DD'),
    startTime: '18:00:00',
    endTime: '18:30:00',
    duration: '30:00',
    size: '480 MB',
    type: 'scheduled',
    thumbnail: null,
  },
  {
    id: 'rec_004',
    cameraId: 'cam_001',
    date: moment().subtract(1, 'days').format('YYYY-MM-DD'),
    startTime: '02:30:00',
    endTime: '02:35:45',
    duration: '5:45',
    size: '89 MB',
    type: 'motion',
    thumbnail: null,
  },
  {
    id: 'rec_005',
    cameraId: 'cam_001',
    date: moment().subtract(2, 'days').format('YYYY-MM-DD'),
    startTime: '08:00:00',
    endTime: '08:15:00',
    duration: '15:00',
    size: '238 MB',
    type: 'motion',
    thumbnail: null,
  },
];

export const mockActivityData = {
  labels: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
  datasets: [
    {
      data: [12, 8, 15, 6, 22, 18, 9],
      color: (opacity = 1) => `rgba(26, 115, 232, ${opacity})`,
      strokeWidth: 2,
    },
  ],
};

export const mockSystemStatus = {
  isArmed: true,
  doorLocked: true,
  lightOn: false,
  gateOpen: false,
  lastUpdate: moment().toISOString(),
};
